name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh-keyscan "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          APP_PORT_INTERNAL: "8062"   # порт, на котором слушает приложение в контейнере
          APP_PORT_EXTERNAL: "60080"  # внешний порт сервера
        run: |
          ssh "$SSH_USER@$SSH_HOST" <<'EOF'
          set -e
          cd /home/hawking/kubsu-linups  # замените на свой путь
          git pull
          docker build -t kubsu:latest .
          docker rm -f kubsu-app || true
          docker run -d --restart=always --name kubsu-app \
              -p ${APP_PORT_EXTERNAL}:${APP_PORT_INTERNAL} \
              kubsu:latest
          EOF
